### ISSUE TITLE
failed to authorize shodan

### ISSUE THREAD

**Issue by nasim13028** [EntySec/CamOver#16]
it says failed to authorize shodan everytime when i use ur key or my key

**Comment by enty8080** [comment]
Yep, that's the problem with shodan, trying to figure it out. You may use Zoomeye instead for now.

**Comment by enty8080** [comment]
@nasim13028 I've got some information on this issue. Seems like in order to use Shodan API and make queries, you need to pay - [click](https://github.com/achillean/shodan-python/issues/187). Thats actually a shame, thats why I'll soon replace Shodan option with Censys. Have you heard about Censys?
