### ISSUE TITLE
Could not build wheels for lxml, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by Phishacker** [EntySec/CamOver#18]
Could not build wheels for lxml, which is required to install pyproject.toml-based 
![Screenshot_2023-11-27-12-55-09-38_84d3000e3f4017145260f7618db1d683](https://github.com/EntySec/CamOver/assets/151625143/d72dea95-6990-4dd5-be81-f9d212c4abbf)
![Uploading Screenshot_2023-11-27-12-55-09-38_84d3000e3f4017145260f7618db1d683.jpg…]()

**Comment by b9Joker108** [comment]
I have the same error.

**Comment by enty8080** [comment]
@Phishacker I don't know why this error appears. I guess the problem is that Termux incorrectly installs XML. CamOver is not designed to run in Termux though.
