### ISSUE TITLE
Failed to Authorize Shodan

### ISSUE THREAD

**Issue by jJit0** [EntySec/CamOver#2]
Hi,

When I type this command `camover -t --shodan PSKINdQe1GyxGgecYz2191H2JoS9qvgD` I get an error
`[*] Authorizing Shodan by given API key...`
`[-] Failed to authorize Shodan!`

Any ideas ?

**Comment by enty8080** [comment]
Hello, @jJit0 

This is problem in API key. There are two solutions for this problem:

* **1.** - retry after some time.
* **2.** - register your own API key at shodan.io

Regards,
Ivan Nikolsky (@enty8080)
