### ISSUE TITLE
'camover' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by unpeko** [EntySec/CamOver#23]
I installed CamOver using the documented method: `pip3 install git+https://github.com/EntySec/CamOver`. However, I encountered the following issue during the execution of the tool.

**Steps to Reproduce:**
1. Installed CamOver using `pip3 install git+https://github.com/EntySec/CamOver`.
2. Executed the tool with a specific command or input.
3. Observed the issue described below.

**Issue:**
'camover' is not recognized as an internal or external command, operable program or batch file.

**Screenshots:**
![image](https://github.com/EntySec/CamOver/assets/132242919/cb38a1b6-2fae-4e38-8bc4-a2f0a0e06c6b)

**Environment:**
- Operating System: Windows 10 (64-bit)

**Workarounds Tried:**
I attempted to install CamOver using the following method:

bash

pip3 install -t . git+https://github.com/EntySec/CamOver

Following the installation, I manually navigated to the CamOver folder. In an attempt to run the tool, I executed the __main__.py script. However, I encountered difficulties and eventually abandoned the process.

**Comment by enty8080** [comment]
Sorry, CamOver is not supported on Windows. However, you might want to check if PATH is set.
