### ISSUE TITLE
Failed to Authorize Shodan

### ISSUE THREAD

**Issue by Darkhaxxor005** [EntySec/CamOver#26]
[*] Authorizing Shodan by given API key...
[-] Failed to authorize Shodan!

**Comment by enty8080** [comment]
@Darkhaxxor005 Seems like you provided invalid API key because it works fine with a valid API key (may be something with your Shodan plan)

**Comment by Darkhaxxor005** [comment]
> @Darkhaxxor005 Seems like you provided invalid API key because it works fine with a valid API key (may be something with your Shodan plan)

Free plan API doesn't work ? I tried multiple API also tried zoomapi both didn't worked

**Comment by enty8080** [comment]
I am afraid yes, it does not work with free plan anymore (I have a membership plan, so it works fine for me). I am currently working on a solution.
