### ISSUE TITLE
Search Shodan by Country/City

### ISSUE THREAD

**Issue by pispuso** [EntySec/CamOver#4]
Hello!

Is there any way to search in Shodan by country and/or city?

In the past, when Entynet Project was alive, I remember editing the source of Entropy to modify the Shodan.query but I can't find a way.

Any help is welcomed.

Thanks!

**Comment by enty8080** [comment]
Hello, @pispuso 

You can find a line connected with Shodan here:

https://github.com/EntySec/CamOver/blob/3689c3ba5eddf822446f04536adaeeedfb2817b7/camover/cli.py#L136

Edit it as you want.

Best regards,
Ivan Nikolsky (@enty8080)
